-- Testbench: drives viterbi_k7_decoder with stimulus.txt (generated by
-- gen_stimulus_soft.py from golden_reference.py's soft_viterbi_decode over
-- a real BPSK+AWGN channel model) and checks the RTL's decoded output
-- matches the Python model's decoded output bit-for-bit, for both cases
-- where decoding recovers the original message and cases where it
-- legitimately does not (noise exceeded correction capacity in both
-- implementations identically).

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb_viterbi_k7 is
end entity tb_viterbi_k7;

architecture sim of tb_viterbi_k7 is

    constant MAX_LEN    : integer := 1504;
    constant CLK_PERIOD : time := 10 ns;
    constant MAX_STR    : integer := 8192;

    signal clk          : std_logic := '0';
    signal rst          : std_logic := '1';
    signal sym0         : std_logic_vector(2 downto 0) := (others => '0');
    signal sym1         : std_logic_vector(2 downto 0) := (others => '0');
    signal erase        : std_logic_vector(1 downto 0) := (others => '0');
    signal din_valid    : std_logic := '0';
    signal din_accept   : std_logic;
    signal frame_start  : std_logic := '0';
    signal frame_end    : std_logic := '0';
    signal decoded_bits : std_logic_vector(MAX_LEN - 1 downto 0);
    signal decode_len   : std_logic_vector(10 downto 0);
    signal decode_done  : std_logic;
    signal busy         : std_logic;

    signal sim_running  : boolean := true;

    procedure read_token(l : inout line; tok : out string; tok_len : out integer) is
        variable c    : character;
        variable good : boolean;
        variable i    : integer := 0;
    begin
        loop
            read(l, c, good);
            exit when not good or c /= ' ';
        end loop;
        while good and c /= ' ' loop
            i := i + 1;
            tok(i) := c;
            read(l, c, good);
        end loop;
        tok_len := i;
    end procedure;

    -- '0'..'7' -> 3-bit unsigned soft value.
    function char_to_sym(c : character) return std_logic_vector is
    begin
        return std_logic_vector(to_unsigned(character'pos(c) - character'pos('0'), 3));
    end function;

begin

    dut: entity work.viterbi_k7_decoder
        generic map (MAX_FRAME_LEN => MAX_LEN)
        port map (
            clk           => clk,
            rst           => rst,
            sym0          => sym0,
            sym1          => sym1,
            erase         => erase,
            input_valid   => din_valid,
            input_accept  => din_accept,
            frame_start   => frame_start,
            frame_end     => frame_end,
            decoded_bits  => decoded_bits,
            decode_len    => decode_len,
            decode_done   => decode_done,
            busy          => busy
        );

    clk_proc: process
    begin
        while sim_running loop
            clk <= '0'; wait for CLK_PERIOD / 2;
            clk <= '1'; wait for CLK_PERIOD / 2;
        end loop;
        wait;
    end process;

    stim_proc: process
        file stim_file      : text open read_mode is "stimulus.txt";
        variable line_v      : line;
        variable num_cases   : integer;
        variable len_tok     : string(1 to 32);
        variable len_tok_len : integer;
        variable sym_tok     : string(1 to MAX_STR);
        variable sym_len     : integer;
        variable erase_tok   : string(1 to MAX_STR);
        variable erase_len   : integer;
        variable exp_tok     : string(1 to MAX_STR);
        variable exp_len     : integer;
        variable frame_len   : integer;
        variable pass_count  : integer := 0;
        variable fail_count  : integer := 0;
        variable mismatch    : boolean;
    begin
        rst <= '1';
        wait for CLK_PERIOD * 5;
        rst <= '0';
        wait for CLK_PERIOD * 2;

        readline(stim_file, line_v);
        read(line_v, num_cases);

        for case_i in 1 to num_cases loop
            readline(stim_file, line_v);
            read_token(line_v, len_tok, len_tok_len);
            frame_len := integer'value(len_tok(1 to len_tok_len));
            read_token(line_v, sym_tok, sym_len);
            read_token(line_v, erase_tok, erase_len);
            read_token(line_v, exp_tok, exp_len);

            wait until rising_edge(clk);
            for sym in 0 to frame_len - 1 loop
                sym0 <= char_to_sym(sym_tok(2 * sym + 1));
                sym1 <= char_to_sym(sym_tok(2 * sym + 2));
                if erase_tok(2 * sym + 1) = '1' then erase(0) <= '1'; else erase(0) <= '0'; end if;
                if erase_tok(2 * sym + 2) = '1' then erase(1) <= '1'; else erase(1) <= '0'; end if;
                din_valid   <= '1';
                if sym = 0 then frame_start <= '1'; else frame_start <= '0'; end if;
                if sym = frame_len - 1 then frame_end <= '1'; else frame_end <= '0'; end if;
                wait until rising_edge(clk);
            end loop;
            din_valid   <= '0';
            frame_start <= '0';
            frame_end   <= '0';

            wait until decode_done = '1';

            mismatch := false;
            if to_integer(unsigned(decode_len)) /= frame_len then
                mismatch := true;
                report "CASE " & integer'image(case_i) & ": length mismatch, RTL=" &
                       integer'image(to_integer(unsigned(decode_len))) & " expected=" & integer'image(frame_len)
                       severity error;
            else
                for b in 0 to frame_len - 1 loop
                    if (decoded_bits(b) = '1' and exp_tok(b + 1) /= '1') or
                       (decoded_bits(b) = '0' and exp_tok(b + 1) /= '0') then
                        mismatch := true;
                    end if;
                end loop;
            end if;

            if mismatch then
                fail_count := fail_count + 1;
                report "CASE " & integer'image(case_i) & " (len=" & integer'image(frame_len) &
                       "): MISMATCH vs golden model" severity error;
            else
                pass_count := pass_count + 1;
                report "CASE " & integer'image(case_i) & " (len=" & integer'image(frame_len) &
                       "): matches golden model bit-for-bit";
            end if;

            wait until rising_edge(clk);
        end loop;

        report "=== TESTBENCH SUMMARY: " & integer'image(pass_count) & " / " &
               integer'image(pass_count + fail_count) & " cases matched the golden model ===";
        sim_running <= false;
        wait;
    end process;

end architecture sim;
